# Generated by Django 3.2.9 on 2021-12-03 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='User UID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Super User')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('user_role', models.CharField(max_length=50, null=True, verbose_name='Role')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
