# Generated by Django 3.2.9 on 2021-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_and_write_doc',
            field=models.BooleanField(default=False, verbose_name='Read and Write'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_only_doc',
            field=models.BooleanField(default=False, verbose_name='Read Only'),
        ),
    ]
