# Generated by Django 3.2.9 on 2021-11-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='read_and_write_doc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='read_only_doc',
        ),
        migrations.AddField(
            model_name='user',
            name='doc_rights',
            field=models.IntegerField(default=0, verbose_name='Document Repo Rights'),
        ),
    ]
