# Generated by Django 3.2.9 on 2021-11-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doc_rights',
        ),
    ]
