# Generated by Django 3.2.9 on 2021-12-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_folder_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Root Folder UID')),
                ('root_folder_name', models.CharField(max_length=255, unique=True, verbose_name='Root Folder Name')),
                ('root_folder_status', models.CharField(default='Active', max_length=20, verbose_name='Root Folder Status')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Root Folder',
                'verbose_name_plural': 'Root Folders',
                'db_table': 'root_folders',
            },
        ),
        migrations.CreateModel(
            name='SubFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_folder_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Sub Folder UID')),
                ('sub_folder_name', models.CharField(max_length=255, unique=True, verbose_name='Sub Folder Name')),
                ('sub_folder_status', models.CharField(default='Active', max_length=20, verbose_name='Sub Folder Status')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('root_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='system_admin.rootfolders', verbose_name='Root Folder')),
            ],
            options={
                'verbose_name': 'Sub Folder',
                'verbose_name_plural': 'Sub Folders',
                'db_table': 'sub_folders',
            },
        ),
        migrations.CreateModel(
            name='DocumentsRepoSubRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Right UID')),
                ('document_right', models.CharField(max_length=255, verbose_name='Document Right')),
                ('document_sub_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.subfolders', verbose_name='Sub Folder')),
                ('rights_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rights To')),
            ],
            options={
                'verbose_name': 'Document Repository Rights',
                'verbose_name_plural': 'Document Repositorys Rights',
                'db_table': 'document_repo_rights',
            },
        ),
        migrations.CreateModel(
            name='DocumentsRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Document UID')),
                ('document_name', models.CharField(max_length=255, unique=True, verbose_name='Document Name')),
                ('disclosure', models.CharField(max_length=50, verbose_name='Disclosure')),
                ('document_path', models.FileField(upload_to='mis_doc_repo/')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('doc_root_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.rootfolders', verbose_name='Root Folder')),
                ('doc_sub_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.subfolders', verbose_name='Sub Folder')),
            ],
            options={
                'verbose_name': 'DocumentRepository',
                'verbose_name_plural': 'DocumentRepositorys',
                'db_table': 'document_repo',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(null=True, verbose_name='About Us')),
                ('date_created', models.DateField(auto_now=True, verbose_name='date_created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='date_modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'about_us',
            },
        ),
    ]
