# Generated by Django 3.2.9 on 2021-11-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_folder_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Root Folder UID')),
                ('root_folder_name', models.EmailField(max_length=255, unique=True, verbose_name='Root Folder Name')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Root Folder',
                'verbose_name_plural': 'Root Folders',
                'db_table': 'root_folders',
            },
        ),
        migrations.CreateModel(
            name='SubFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_folder_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Sub Folder UID')),
                ('sub_folder_name', models.EmailField(max_length=255, unique=True, verbose_name='Sub Folder Name')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('root_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='system_admin.rootfolders', verbose_name='Root Folder')),
            ],
            options={
                'verbose_name': 'Sub Folder',
                'verbose_name_plural': 'Sub Folders',
                'db_table': 'sub_folders',
            },
        ),
    ]
