# Generated by Django 3.2.9 on 2021-11-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfolders',
            name='root_folder_status',
            field=models.EmailField(default=True, max_length=20, unique=True, verbose_name='Root Folder Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfolders',
            name='sub_folder_status',
            field=models.EmailField(default=True, max_length=20, verbose_name='Sub Folder Status'),
            preserve_default=False,
        ),
    ]
