# Generated by Django 3.2.9 on 2021-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_auto_20211121_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootfolders',
            name='root_folder_status',
            field=models.EmailField(default='Active', max_length=20, verbose_name='Root Folder Status'),
        ),
    ]
