# Generated by Django 3.2.9 on 2021-12-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0003_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='CoreSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_we_work', models.TextField(null=True, verbose_name='Where We Work')),
                ('core_sites', models.TextField(null=True, verbose_name='Core Sites')),
                ('isf_sites', models.TextField(null=True, verbose_name='ISF Sites')),
                ('remidial_work_sites', models.TextField(null=True, verbose_name='Remidial Works Sites')),
                ('date_created', models.DateField(auto_now=True, verbose_name='date_created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Core Site',
                'verbose_name_plural': 'Core Sites',
                'db_table': 'where_we_work',
            },
        ),
    ]
