# Generated by Django 3.2.9 on 2021-11-22 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0004_alter_rootfolders_root_folder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootfolders',
            name='root_folder_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Root Folder Name'),
        ),
        migrations.AlterField(
            model_name='rootfolders',
            name='root_folder_status',
            field=models.CharField(default='Active', max_length=20, verbose_name='Root Folder Status'),
        ),
        migrations.AlterField(
            model_name='subfolders',
            name='sub_folder_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sub Folder Name'),
        ),
        migrations.AlterField(
            model_name='subfolders',
            name='sub_folder_status',
            field=models.CharField(default='Active', max_length=20, verbose_name='Sub Folder Status'),
        ),
        migrations.CreateModel(
            name='DocumentsRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Document UID')),
                ('document_name', models.CharField(max_length=255, unique=True, verbose_name='Document Name')),
                ('disclosure', models.CharField(max_length=50, verbose_name='Disclosure')),
                ('document_path', models.FileField(upload_to='mis_doc_repo/')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('doc_root_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.rootfolders', verbose_name='Root Folder')),
                ('doc_sub_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.subfolders', verbose_name='Sub Folder')),
            ],
            options={
                'verbose_name': 'DocumentRepository',
                'verbose_name_plural': 'DocumentRepositorys',
                'db_table': 'document_repo',
            },
        ),
    ]
