# Generated by Django 3.2.9 on 2021-11-27 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0005_auto_20211122_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRepoSubRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Right UID')),
                ('document_right', models.CharField(max_length=255, unique=True, verbose_name='Document Right')),
                ('document_sub_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.subfolders', verbose_name='Sub Folder')),
                ('rights_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rights To')),
            ],
            options={
                'verbose_name': 'Document Repository Rights',
                'verbose_name_plural': 'Document Repositorys Rights',
                'db_table': 'document_repo_rights',
            },
        ),
    ]
