# Generated by Django 3.2.9 on 2021-11-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0006_documentsreposubrights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsreposubrights',
            name='document_right',
            field=models.CharField(max_length=255, verbose_name='Document Right'),
        ),
    ]
